# Site settings
baseURL = "https://tatsuroro.com/"
languageCode = "ja-JP"
title = "tatsuroro.com"
theme = "hugo-theme-cactus-plus"
# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-45922705-1"
hasCJKLanguage = true

[params]
	name = "tatsuroro.com"
  description = "Frontend developer, working from Fukuoka, Japan."
  bio = ""
	# Enter optionally your twitter account
	twitter = "tatsuroro"
	enableRSS = true

	# Disqus comment
	disqusShortname = "tatsuroro-com"
	# Disable disqus comments by set `enableDisqus = "false"`
	enableDisqus = true

	# Duoshuo comment
	duoshuoShortname = "your_duoshuo_short_name"
	# Disable duoshuo comments by set `enableDuoshuo = "false"`
	enableDuoshuo = false

	enableGithubIssuesTips = false

	# Enable googleAnalytics
	enableGoogleAnalytics = true

	# Enable baiduAnalytics
	enableBaiduAnalytics = false
	# Baidu Tongji Code
	baiduAnalytics = 'your_baidu_tongji_code'

	# Add custom assets with their paths relative to the static folder
	customCSS = ['css/custom.css']
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	about = ""
	archive = ""
	subscribe = ""
	tags = ""
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = ""
	# Sharing options and author information in posts
	aboutAuthor = "I am so interesting."
	tweet = ""
	share = ""
	# 404 page
	title404 = ""
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "mono-social"
  # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
  socialIconStyle = "circle"

# Add additional social link entries underneath
[social]
	githubalt = "https://github.com/tatsuroro"
  twitter = "https://twitter.com/tatsuroro"
